package main

// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

type CreateTodoRequestInput struct {
	Title string `json:"title"`
}

// __todoServiceCreateTodoInput is used internally by genqlient
type __todoServiceCreateTodoInput struct {
	In CreateTodoRequestInput `json:"in"`
}

// todoServiceCreateTodoResponse is returned by todoServiceCreateTodo on success.
type todoServiceCreateTodoResponse struct {
	TodoServiceCreateTodo todoServiceCreateTodoTodoServiceCreateTodoCreateTodoResponse `json:"todoServiceCreateTodo"`
}

// todoServiceCreateTodoTodoServiceCreateTodoCreateTodoResponse includes the requested fields of the GraphQL type CreateTodoResponse.
type todoServiceCreateTodoTodoServiceCreateTodoCreateTodoResponse struct {
	Id string `json:"id"`
}

func todoServiceCreateTodo(
	ctx context.Context,
	client graphql.Client,
	in CreateTodoRequestInput,
) (*todoServiceCreateTodoResponse, error) {
	__input := __todoServiceCreateTodoInput{
		In: in,
	}
	var err error

	var retval todoServiceCreateTodoResponse
	err = client.MakeRequest(
		ctx,
		"todoServiceCreateTodo",
		`
mutation todoServiceCreateTodo ($in: CreateTodoRequestInput!) {
	todoServiceCreateTodo(in: $in) {
		id
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}
